"
"  Doug's VIM initialization file
"

" Vundle setup and load plugins
"   https://github.com/gmarik/Vundle.vim
set nocompatible        " don't try to be compatible with vi
filetype off

set rtp+=~/.vim/bundle/Vundle.vim/
set rtp+=/usr/local/opt/fzf
call vundle#begin()

" Core plugins
Plugin 'VundleVim/Vundle.vim'       " package management
Plugin 'jlanzarotta/bufexplorer'    " better buffer list

" Main plugins
" Plugin 'scrooloose/syntastic'
Plugin 'dense-analysis/ale'         " async syntax checking, plus other stuff
Plugin 'prabirshrestha/asyncomplete.vim'
Plugin 'OmniSharp/omnisharp-vim'    " C#

" Experimental
" Plugin 'ledger/vim-ledger'                  " support for ledger files
" Plugin 'nathangrigg/vim-beancount'          " support for beancount files

" Plugin 'mileszs/ack.vim'                    " search using Ack
" Plugin 'ctrlpvim/ctrlp.vim'                 " fuzzy file finder
" Plugin '/usr/local/opt/fzf'
Plugin 'junegunn/fzf.vim'
Plugin 'hashivim/vim-terraform'
Plugin 'tpope/vim-vinegar'                 " enhancements to netrw

" Plugin 'ConradIrwin/vim-bracketed-paste'    " automagically set paste when pasting
" Plugin 'HerringtonDarkholme/yats.vim'       " Typescript syntax highlighting
" Plugin 'tpope/vim-surround'                 " surround
" Plugin 'tpope/vim-repeat'                   " repeat support for surround and other plugins
" Plugin 'tpope/vim-commentary'               " support for commenting things out
" Plugin 'ludovicchabant/vim-gutentags'       " better tags support?
" Plugin 'davidhalter/jedi-vim'               " Python code completion, via Jedi
" Plugin 'Glench/Vim-Jinja2-Syntax'           " Jinja2 syntax

" Remapping the tab key seems to mess me up more often than it helps
" Plugin 'ervandew/supertab'          " tab completion

" airline does not work right in WSL
" Plugin 'vim-airline/vim-airline'    " fancy status bar
" Plugin 'vim-airline/vim-airline-themes'

" Language-specific
" Plugin 'fatih/vim-go'           " Support for go

" Python
" Always folds everything up on file open; ick.
" Plugin 'tmhedberg/SimpylFold'       " folding


call vundle#end()            " required
filetype plugin indent on    " required

syntax on               " syntax coloring is very cool...turn it on...
" syntax sync fromstart
" colorscheme default   " comments too light on WSL
" colorscheme slate     " highlight in quickfix unreadable
colorscheme elflord

set autoindent          " always set autoindenting on
set expandtab           " spaces instead of tabs
set hidden              " keep hidden buffers
set incsearch           " show search progress
set laststatus=2        " always show a status line
" set makeprg=xbuild      " doing mono development by default
set ruler               " show line,column in status line
set scrolloff=1         " keep a couple of lines above/below cursor
set shiftround          " round indent when using > and <
set shiftwidth=4        " when indenting, use 4 spaces
set shortmess=a         " abbreviate messages to get rid of [hit return] prompts
set showcmd             " show partial commands in status line
set tabstop=4           " work like the rest of marketwatch
set viminfo='50,/10     " save last ten find commands in viminfo file
set visualbell          " flash screen instead of beeping
set nowrap              " don't wrap lines
set wrapscan            " wrap searches around end of file
" set wildmenu

" set t_BE=               " disable bracketed paste in iterm2

set number              " show line numbers
set relativenumber      " ...and make 'em relative

set statusline =
" Buffer number
set statusline +=[%n] 
" File description
set statusline +=\ %f\ %h%m%r%w
" Name of the current branch (needs fugitive.vim)
" set statusline +=\ %{fugitive#statusline()}
" Date of the last time the file was saved
" set statusline +=\ %{strftime(\"[%d/%m/%y\ %T]\",getftime(expand(\"%:p\")))} 
" Total number of lines in the file
set statusline +=%=%-10L
" Line, column and percentage
set statusline +=%=%-14.(%l,%c%V%)
" Filetype
set statusline +=\ %y

" Enable folding
" set foldmethod=indent
set foldlevel=99

" file type: .sh
augroup filetype_sh
    autocmd!
    " set up tabs
    autocmd FileType sh setlocal shiftwidth=2 tabstop=2
augroup end

" file type: .json
augroup filetype_json
    autocmd!
    autocmd FileType json setlocal foldmethod=syntax foldlevel=20
augroup end

" file type: .yaml
augroup filetype_yaml
    autocmd!
    autocmd FileType yaml setlocal foldmethod=indent foldlevel=20
augroup end

" file type: ALL
augroup filetype_all
    autocmd!
    " do not automatically add comments to new lines
    autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o
augroup end

set tags=./tags;/		" look in current and all parent directories for tags file

let mapleader=","

" - - - - BufExplorer Setup
let g:bufExplorerDisableDefaultKeyMapping=1
nnoremap <leader>b :BufExplorerHorizontalSplit<CR>

" - - - - Syntastic setup
" let g:syntastic_enable_signs = 1
" let g:syntastic_check_on_open = 0
" let g:syntastic_check_on_wq = 0
" let g:syntastic_enable_highlighting = 0
" let g:syntastic_always_populate_loc_list = 1    " can use :lnext and :lprev to move between errors
" let g:syntastic_auto_loc_list = 1

" let g:syntastic_python_checkers = ['flake8']
" let g:syntastic_python_flake8_post_args="--max-line-length=175"

" let g:syntastic_html_checkers=['']
" let g:syntastic_asm_compiler=''

" let g:syntastic_go_checkers = [ 'gofmt' ]

" Disable java
" let g:loaded_syntastic_java_javac_checker = 1

" nnoremap <leader>sc :SyntasticReset<CR>
" nnoremap <leader>ss :SyntasticCheck<CR>

" let g:syntastic_ruby_mri_quiet_messages = { "regex": 'assigned but unused variable' }

" - - - - vim-go setup
" let g:go_fmt_fail_silently = 1
let g:go_template_autocreate = 0

let g:go_fmt_autosave = 1
let g:go_fmt_fail_silently = 1
let g:go_fmt_command = "goimports"
" let g:go_list_type = "locationlist"

" let g:go_fmt_options = {
"     \ 'goimports': '-local mycompany.com',
"     \ }

" - - - - netrw setup (built-in file browser)

" Hide all dot files, use gh to toggle
let g:netrw_list_hide = '\(^\|\s\s\)\zs\.\S\+'

" - - - - omnisharp setup

" Use the stdio OmniSharp-roslyn server
let g:OmniSharp_server_stdio = 1

augroup omnisharp_commands
    autocmd!

    " The following commands are contextual, based on the cursor position.
    autocmd FileType cs nnoremap <buffer> gd :OmniSharpGotoDefinition<CR>
    autocmd FileType cs nnoremap <buffer> <Leader>fi :OmniSharpFindImplementations<CR>
    autocmd FileType cs nnoremap <buffer> <Leader>fs :OmniSharpFindSymbol<CR>
    autocmd FileType cs nnoremap <buffer> <Leader>fu :OmniSharpFindUsages<CR>

    " Finds members in the current buffer
    autocmd FileType cs nnoremap <buffer> <Leader>fm :OmniSharpFindMembers<CR>

    " Display the type name/documentation/signature of symbol under the cursor
    autocmd FileType cs nnoremap <buffer> <Leader>ft :OmniSharpTypeLookup<CR>
    autocmd FileType cs nnoremap <buffer> <Leader>fd :OmniSharpDocumentation<CR>
    autocmd FileType cs nnoremap <buffer> <Leader>fg :OmniSharpSignatureHelp<CR>

    " Fuzzy-search thru code actions
    autocmd FileType cs nnoremap <buffer> <Leader>ff :OmniSharpGetCodeActions<CR>

    " Populate quickfix with all code issues in solution
    autocmd FileType cs nnoremap <buffer> <Leader>fb :OmniSharpGlobalCodeCheck<CR>

    " Navigate between methods/classes
    autocmd FileType cs nnoremap <buffer> <Leader>f<Up> :OmniSharpNavigateUp<CR>
    autocmd FileType cs nnoremap <buffer> <Leader>f<Down> :OmniSharpNavigateDown<CR>

    " Fix usings
    autocmd FileType cs nnoremap <buffer> <Leader>fx :OmniSharpFixUsings<CR>
augroup END

" - - - - asynccomplete setup

" Completion mappings
inoremap <expr> j     pumvisible() ? "\<C-n>" : "j"
inoremap <expr> k     pumvisible() ? "\<C-p>" : "k"
inoremap <expr> <cr>  pumvisible() ? "\<C-y>" : "\<cr>"
inoremap <expr> <Esc> pumvisible() ? "\<C-e>" : "\<Esc>"

" Don't pop up the popup until asked
let g:asyncomplete_auto_popup = 0

" Set colors (not really part of the plugin, but used for completion)
highlight Pmenu ctermbg=White ctermfg=Gray
highlight PmenuSel ctermbg=DarkRed ctermfg=White


" - - - - ALE setup

nnoremap <silent> <leader>ad :ALEDisableBuffer<cr>
nnoremap <silent> <leader>ae :ALEEnableBuffer<cr>
nmap <silent> <leader>an <Plug>(ale_next_wrap)
nmap <silent> <leader>ap <Plug>(ale_previous_wrap)

" Use quickfix instead of loclist
let g:ale_set_loclist = 0
let g:ale_set_quickfix = 1

highlight ALEError ctermbg=none cterm=underline
highlight ALEWarning ctermbg=none cterm=underline
highlight ALEInfo ctermbg=none cterm=underline

" - - - - Custom Mappings
nnoremap <leader>e :Explore<cr>

nnoremap <leader>ve :edit $MYVIMRC<cr>
nnoremap <leader>vs :source $MYVIMRC<cr>

nnoremap <leader>qc :cclose<cr>
nnoremap <leader>qf :cfirst<cr>
nnoremap <leader>ql :clast<cr>
nnoremap <leader>qn :cnext<cr>
nnoremap <leader>qo :copen<cr>
nnoremap <leader>qp :cprev<cr>

" Close the quickfix window when item is selected
:autocmd FileType qf nnoremap <buffer> <CR> <CR>:cclose<CR>

" Map auto-complete to ctrl-space: https://stackoverflow.com/q/7722177
" inoremap <C-Space> <C-x><C-o>
" imap <C-@> <C-Space>
inoremap <C-@> <c-x><c-o>

" Remap jk to esc in insert mode and disable esc to force usage
inoremap jk <esc>
" inoremap <esc> <nop>

