
if [ -e .zshrc-local-pre ]; then
    source .zshrc-local-pre
fi

# Based on https://dougblack.io/words/zsh-vi-mode.html
# and http://zanshin.net/2013/02/02/zsh-configuration-from-the-ground-up/

# Set up history file
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

# Set vi command-line editing mode
bindkey -v

# Have info use vi key bindings; an alias seems to be the only way
alias info='info --vi-keys'

# Enable highlighting in less
alias less='less -R'

#function zle-line-init zle-keymap-select {
#    VIM_PROMPT="%{$fg_bold[yellow]%} [% NORMAL]%  %{$reset_color%}"
#    # RPS1="${${KEYMAP/vicmd/$VIM_PROMPT}/(main|viins)/}$(git_custom_status) $EPS1"
#    RPS1="${${KEYMAP/vicmd/$VIM_PROMPT}/(main|viins)/} $EPS1"
#    zle reset-prompt
#}

#zle -N zle-line-init
#zle -N zle-keymap-select
#export KEYTIMEOUT=1

# Clear LSCOLORS
unset LSCOLORS

# Make directories more visible on a dark background
export CLICOLOR=1
export LSCOLORS=Gxfxcxdxbxegedabagacad

# try to make git happy with the editor
export EDITOR=/usr/bin/vim

# playing with GO; this is probably wrong...
if [ -d /home/swish/git/waiig ]; then
    export GOPATH=/home/swish/git/waiig
fi

# my virtualenv wrapper
export VENV_DIR=~/VirtualEnvs
source ~/git/dothome/myvirtualenv.sh

# TODO - figure out this bit
# The following lines were added by compinstall
# zstyle :compinstall filename '$HOME/.zshrc'

# autoload -Uz compinit
# compinit
# End of lines added by compinstall

# Put local bin in path
export PATH="$HOME/bin:$PATH"

if [ -e .zshrc-local-post ]; then
    source .zshrc-local-post
fi

# pyenv support (if installed)
if [ -d $HOME/.pyenv ]; then
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"

    eval "$(pyenv init -)"

    if [ -f $HOME/.pyenv/shims/virtualenv ]; then
        eval "$(pyenv virtualenv-init -)"
    fi
fi

# jenv support (if installed)
if [ -d $HOME/.jenv ]; then
    export PATH="$HOME/.jenv/bin:$PATH"
    eval "$(jenv init -)"
fi

# Experimental stuff
function up {
    if [[ "$#" < 1 ]] ; then
        cd ..
    else
        CDSTR=""
        for i in {1..$1} ; do
            CDSTR="../$CDSTR"
        done
        cd $CDSTR
    fi
}

